const fs = require("fs");
const https = require("https");

const players = [
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Kylian Mbappé",
  "Erling Haaland",
  "Neymar Jr.",
  "Kevin De Bruyne",
  "Vinicius Jr.",
  "Mohamed Salah",
  "Robert Lewandowski",
  "Luka Modrić",
  "Harry Kane",
  "Virgil van Dijk",
  "Pedri",
  "Jude Bellingham",
  "Thibaut Courtois",
  "Lamine Yamal",
  "Bukayo Saka",
  "Florian Wirtz",
  "Jamal Musiala",
  "Rodri",
  "Cole Palmer",
  "Phil Foden",
  "Declan Rice",
  "Federico Valverde",
  "Trent Alexander-Arnold",
  "Rúben Dias",
  "Gianluigi Donnarumma",
  "Antoine Griezmann",
  "Son Heung-min",
  "Bernardo Silva",
  "Alexia Putellas",
  "Aitana Bonmatí",
  "Julian Álvarez",
  "Alisson Becker",
  "Alexander Isak",
  "Zinedine Zidane",
  "Ronaldinho",
  "Thierry Henry",
  "Ronaldo Nazário",
  "Zlatan Ibrahimovic",
  "Paolo Maldini",
  "Gianluigi Buffon",
  "Xavi Hernandez",
  "Andrés Iniesta",
  "Sergio Ramos",
  "Iker Casillas",
  "Cafu",
  "Roberto Carlos",
  "Rivaldo",
  "Fabio Cannavaro",
  "Oliver Kahn",
  "Didier Drogba",
  "Samuel Eto'o",
  "Ruud van Nistelrooy",
  "Patrick Vieira",
  "Ronaldo de Lima",
  "Kaká",
  "Franck Ribéry",
  "Wayne Rooney",
  "Arjen Robben",
  "Filippo Inzaghi",
  "Clarence Seedorf",
  "Lev Yashin",
  "Johan Cruyff",
  "Franz Beckenbauer",
  "Ronaldo Luis",
  "Pep Guardiola",
  "Luis Figo",
  "Michael Owen",
  "Raúl González",
  "George Best",
  "David Beckham",
  "Dennis Bergkamp",
  "Romario",
  "Eusébio",
  "Andrea Pirlo",
  "Rivaldo",
  "Ronaldo de Assis",
  "Riquelme",
  "Steven Gerrard",
  "Frank Lampard",
  "Xabi Alonso",
  "Gareth Bale",
  "Sergio Agüero",
  "Gerd Müller",
  "Marco van Basten",
  "Ruud Gullit",
  "Pelé",
  "Diego Maradona",
  "Ronaldo Luís Nazário de Lima",
  "Lothar Matthäus",
  "Marcel Desailly",
  "Roberto Baggio",
  "Ronaldo de Lima II",
  "Miroslav Klose",
  "Ronaldinho Gaucho",
  "Paolo Maldini",
  "Ryan Giggs",
  "Alessandro Del Piero",
  "Thierry Henry",
];

if (!fs.existsSync("./public/players")) {
  fs.mkdirSync("./public/players");
}

players.forEach((name) => {
  const fileName = name.replace(/ /g, "_");
  const url = `https://ui-avatars.com/api/?name=${name.replace(/ /g, "+")}&size=256`;

  const file = fs.createWriteStream(`./public/players/${fileName}.png`);

  https.get(url, (response) => {
    response.pipe(file);
  });
});
